
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 09 22:58:56 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 17;
  public static final int CONST = 12;
  public static final int NUMCONST = 52;
  public static final int CASE = 41;
  public static final int HASH = 49;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 29;
  public static final int DECR = 16;
  public static final int INCR = 15;
  public static final int MINUS = 30;
  public static final int SQBRR = 10;
  public static final int GREQ = 37;
  public static final int RPAREN = 7;
  public static final int AND = 43;
  public static final int SQBRL = 11;
  public static final int OR = 42;
  public static final int QMARK = 44;
  public static final int COMMA = 8;
  public static final int CLASS = 13;
  public static final int DIV = 18;
  public static final int PLUS = 31;
  public static final int IF = 20;
  public static final int DOT = 14;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 46;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int MOD = 19;
  public static final int IDENT = 54;
  public static final int BREAK = 26;
  public static final int VOID = 25;
  public static final int EQ = 34;
  public static final int SWITCH = 23;
  public static final int COLON = 27;
  public static final int ELSE = 39;
  public static final int LBRACE = 3;
  public static final int ENUM = 45;
  public static final int READ = 40;
  public static final int GOTO = 51;
  public static final int CHARCONST = 53;
  public static final int FINAL = 50;
  public static final int WHILE = 22;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 55;
  public static final int EXTENDS = 24;
  public static final int PROG = 2;
  public static final int LEEQ = 35;
  public static final int AT = 47;
  public static final int SWAP = 48;
  public static final int GR = 36;
  public static final int PRINT = 9;
  public static final int DO = 21;
  public static final int NOTEQ = 38;
}

